# Board 
UNASSIGNED = 0
BOARD_SIZE = 9
THICKNESS = 3
BOARD = [[1,UNASSIGNED,UNASSIGNED,4,8,9,UNASSIGNED,UNASSIGNED,6],
                    [7,3,UNASSIGNED,UNASSIGNED,5,UNASSIGNED,UNASSIGNED,4,UNASSIGNED],
                    [4,6,UNASSIGNED,UNASSIGNED,UNASSIGNED,1,2,9,5],
                    [3,8,7,1,2,UNASSIGNED,6,UNASSIGNED,UNASSIGNED],
                    [5,UNASSIGNED,1,7,UNASSIGNED,3,UNASSIGNED,UNASSIGNED,8],
                    [UNASSIGNED,4,6,UNASSIGNED,9,5,7,1,UNASSIGNED],
                    [9,1,4,6,UNASSIGNED,UNASSIGNED,UNASSIGNED,8,UNASSIGNED],
                    [UNASSIGNED,2,UNASSIGNED,UNASSIGNED,4,UNASSIGNED,UNASSIGNED,3,7],
                    [8,UNASSIGNED,3,5,1,2,UNASSIGNED,UNASSIGNED,4]]

FINISHED_BOARD = [[1,UNASSIGNED,UNASSIGNED,4,8,9,UNASSIGNED,UNASSIGNED,6],
                    [7,3,UNASSIGNED,UNASSIGNED,5,UNASSIGNED,UNASSIGNED,4,UNASSIGNED],
                    [4,6,UNASSIGNED,UNASSIGNED,UNASSIGNED,1,2,9,5],
                    [3,8,7,1,2,UNASSIGNED,6,UNASSIGNED,UNASSIGNED],
                    [5,UNASSIGNED,1,7,UNASSIGNED,3,UNASSIGNED,UNASSIGNED,8],
                    [UNASSIGNED,4,6,UNASSIGNED,9,5,7,1,UNASSIGNED],
                    [9,1,4,6,UNASSIGNED,UNASSIGNED,UNASSIGNED,8,UNASSIGNED],
                    [UNASSIGNED,2,UNASSIGNED,UNASSIGNED,4,UNASSIGNED,UNASSIGNED,3,7],
                    [8,UNASSIGNED,3,5,1,2,UNASSIGNED,UNASSIGNED,4]]

# Pixels
WIDTH, HEIGHT = 600, 600
X_GRID = 75
Y_GRID = 100
CELL_SIZE = 50
GRID_SIZE = CELL_SIZE*BOARD_SIZE

# RGB
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
LIGHTBLUE = (96, 216, 232)
GRAY = (189, 189, 189)
PENCIL_GRAY = (128, 128, 128)
RED = (255, 0, 0)

ENTER = 271